# vi:ft=python fo=qacj

Import('*')

helpers = env.Object('helpers.cpp')
poincare = env.Object('poincare.cpp')

env.Program('infiniboard', ['infiniboard.cpp', helpers, poincare],
        LIBS=['SDL2'] + env.gl_libs)
env.Program('load_test', ['load_test.cpp', helpers],
        LIBS=env.gl_libs)
env.Program('line_strip_to_lines_test', ['line_strip_to_lines_test.cpp',
        helpers], LIBS=env.gl_libs)
